default: &default
  adapter: postgresql
  encoding: unicode
  database: osoc
  pool: 5

development:
  <<: *default
  database: osoc_development

test:
  <<: *default
  database: osoc_test

production:
  <<: *default
  database: osoc_production
  username: osoc
  password: <%= ENV['OSOC_DATABASE_PASSWORD'] %>