# PostgreSQL. Versions 8.2 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  database: railsapp
  pool: 5
  username: postgres
  password:
  host: db

development:
  <<: *default
  database: railsapp_development

test:
  <<: *default
  database: railsapp_test

production:
  <<: *default
  database: railsapp_production
  username: railsapp
  password: <%= ENV['RAILSAPP_DATABASE_PASSWORD'] %>
